version = 0.1
[default.deploy.parameters]
stack_name = "BankingLambdasFinal"
resolve_s3 = true
s3_prefix = "BankingLambdasFinal"
region = "us-east-1"
profile = "ThomasGeanLambdaAccess"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
